name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'subprojects/**'
      - 'meson.build'
      - 'meson_options.txt'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip3 install cpplint==1.6.1 codespell
      - run: |
          cpplint --recursive --quiet .
          codespell -S "docs,build,coverage-report,subprojects"

  test:
    name: test-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Meson and GTK
        run: |
          sudo apt-get update
          sudo apt-get -y install xvfb libgtk-3-dev
          pip3 install meson ninja

      - name: Build and Run Tests
        run: |
          meson setup build
          meson compile -C build
          xvfb-run -a meson test -C build -v
